version: "3.9"
services:
  autolycus:
    image: ghcr.io/duonghaipham/autolycus:latest
    container_name: autolycus
    ports:
      - "9001:3000"
    environment:
      - NODE_ENV=production
    restart: always
