services:
  autolycus:
    image: ghcr.io/duonghaipham/autolycus:latest
    container_name: autolycus
    ports:
      - "9001:3000"
    environment:
      - NODE_ENV=production
    restart: always
  narcissus:
    image: ghcr.io/duonghaipham/narcissus:latest
    container_name: narcissus
    ports:
      - "9002:3000"
    restart: unless-stopped
