name: Support 🔧

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ssh to server to copy files
      - name: Checkout
        uses: actions/checkout@v2

      - name: Zip files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r atlas.zip .

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "atlas.zip"
          target: "~/"

      - name: Unzip files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            rm -rf /usr/local/src/atlas
            sudo mkdir -p /usr/local/src/atlas
            unzip -qq atlas.zip -d /usr/local/src/atlas
            rm -f atlas.zip
